### ISSUE TITLE
How did you draw two CAM in the output picture?

### ISSUE THREAD

**Issue by jianing-sun** [a-ozbek/food-hunter#1]
Hi, when I use CAM for heatmap drawing, it usually only generate one region of heatmap circle. I found in your result of the first picture (two girls with spaghetti) there are two regions of heatmap. How did this come out?  
If I test that pic with your main.py. It only generate a big part heatmap. You can check the pic below:
![multiple_food_out](https://user-images.githubusercontent.com/33068301/45523357-e3d27c80-b796-11e8-96f1-f61ef5fb2327.jpg)

Thanks!

**Comment by a-ozbek** [comment]
I believe that there is no restriction for heatmaps to have only one region.

I think you got a different result because you are using a different resolution of the image. I found and attached the original image from the dataset written on README. If you try with that image, you will see two heatmap regions.

![1_499](https://user-images.githubusercontent.com/14084682/45534578-7af7fe00-b7b0-11e8-9841-a2aa9a893ce3.jpg)

**Comment by jianing-sun** [comment]
@a-ozbek thanks a lot for your quick reply!
I found the main problem is I changed the input size of the preprocess image function (originally it's 299x299). And it seems this parameter only works with the image you offered in README. When I test it with other multi-object food images it still display only one main heatmap in the middle of different food objects. Do you know why? I would like to hear your opinion!

Plus, I assume the number of heatmaps is not relevant with the resolution. Do you think the inputsize parameter of preprocessim() is the only reason account for that? 

Thanks again!

Jianing

**Comment by a-ozbek** [comment]
The heatmap is obtained from the feature maps in the last convolutional layer, those are abstract representations of the input image. It cannot be guaranteed that you will have separate regions for each food in the image. However, what I can say is that you are less likely to have separate regions if the input size is small because of MaxPooling layers.
